### ISSUE TITLE
UndefVarError: HomogenousMesh not defined

### ISSUE THREAD

**Issue by nuclear718** [JuliaGeometry/Descartes.jl#56]
`using Descartes

c = Cuboid([5,5,5])

h = translate([2.5,2.5,0])Cylinder(1,5)

obj = diff(c,h)

m = HomogenousMesh(obj)

save("cube_with_hole.stl", m)`

Return:  **UndefVarError: HomogenousMesh not defined**

_My version info:
Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: AMD Ryzen 5 3600X 6-Core Processor             
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, znver2)
Environment:
  JULIA.EXECUTABLEPATH = C:\Users\USER\AppData\Local\Julia-1.3.1\bin\ & set JULIA_NUM_THREADS=12 & julia.exe
  JULIA_NUM_THREADS = 12_

**Comment by sjkelly** [comment]
You also need `using GeometryBasics`
